test:
  hello1: AbcdEfgh
  hello2: 666666100

server:
  port: 0

info:
  component: Review Core Service


ribbon:
  # Interval to refresh the server list from the source
  serverListRefreshInterval: 1000
#
#  # Connect timeout used by Apache HttpClient
#  connectTimeout: 100
#
#  # Read timeout used by Apache HttpClient
#  readTimeout: 10000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
  port: 8080

app:
  rabbitmq:
    host: rabbitmq

conf:
  couchbase:
    akka:
      timeout: 1000
      execution-context:
        fork-join-executor:
          parallelism-factor: 4.0
          parallelism-max: 40
    buckets:
      - host: couchbase
        port: 8091
        base: pools
        bucket: static_profile
        timeout: 0

---
# For deployment in Cloud Foundry
spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/

